# Generated by Django 5.0.7 on 2024-08-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_description_task_why_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Why',
            new_name='description',
        ),
    ]
